### ISSUE TITLE
ubuntu torpedo launch error

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/gulp#70]
````
time="2015-10-19T15:10:04+02:00" level=debug msg="Clone chef cookbooks" 
time="2015-10-19T15:10:04+02:00" level=debug msg="github Initialized" 
time="2015-10-19T15:10:04+02:00" level=debug msg="chefsolo initialized" 
time="2015-10-19T15:10:04+02:00" level=info msg="chefsolo provisioner reports the following:\n    chef-solo provisioner initiated. " 
time="2015-10-19T15:10:04+02:00" level=debug msg="New bucket: assembly" 
time="2015-10-19T15:10:04+02:00" level=debug msg="[riak] open ([192.168.1.105:8087]) SUCCESS" 
time="2015-10-19T15:10:04+02:00" level=debug msg="[riak] closing..." 
time="2015-10-19T15:10:04+02:00" level=debug msg="[pipeline] running the Forward for the update-ip-riak action" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x557354]

goroutine 1 [running]:
github.com/megamsys/gulp/carton.(*Ambly).SetIPAddress(0x0, 0xc8201474d0, 0xc, 0x0, 0x0)
	/home/thomas/code/megam/workspace/packager/megamgulpd/build/trusty/gulp/src/github.com/megamsys/gulp/carton/assembly.go:229 +0xc4
github.com/megamsys/gulp/subd/gulpd.glob.func5(0x0, 0x0, 0xc820147380, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/thomas/code/megam/workspace/packager/megamgulpd/build/trusty/gulp/src/github.com/megamsys/gulp/subd/gulpd/actions.go:83 +0x12e
github.com/megamsys/libgo/action.(*Pipeline).Execute(0xc82000f0c0, 0xc820147380, 0x1, 0x1, 0x0, 0x0)
	/home/thomas/.go/src/github.com/megamsys/libgo/action/action.go:141 +0x7da
github.com/megamsys/gulp/subd/gulpd.(*Service).updateStatusPipeline(0xc820114c00, 0x0, 0x0)

**Comment by indykish** [comment]
@thomasalrin  Check it out, and close this issue.
